seminarios_index:
    path:     /
    defaults: { _controller: "AppBundle:Seminarios:index" }
    methods:  GET

seminarios_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Seminarios:show" }
    methods:  GET

seminarios_new:
    path:     /new
    defaults: { _controller: "AppBundle:Seminarios:new" }
    methods:  [GET, POST]

seminarios_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Seminarios:edit" }
    methods:  [GET, POST]

seminarios_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Seminarios:delete" }
    methods:  DELETE
